name: .NET 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore FsSolution/FProj.fsproj

    - name: Build project
      run: dotnet build ./FsSolution/
 
    - name: Set DOTNET_ROLL_FORWARD
      run: echo "DOTNET_ROLL_FORWARD=latestMajor" >> $GITHUB_ENV
    - name: Lint
      run: |
          dotnet tool install -g dotnet-fsharplint
          dotnet fsharplint lint ./FsSolution/

    - name: Formatter
      run: |
          dotnet tool install -g fantomas-tool
          fantomas ./FsSolution/*.fs 
        
    - name: Run project
      run: dotnet run --project ./FsSolution/
        
    - name: Tests
      run: |
            dotnet restore Tests/Tests.fsproj
            dotnet build ./Tests
            dotnet test ./Tests