name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install FSharpLint
      run: dotnet tool install -g dotnet-fsharplint

    - name: Install FSharpLint
      run: dotnet tool install -g fantomas

    - name: Restore dependencies
      run: dotnet restore 

    - name: Build the project
      run: dotnet build --no-restore

    - name: Linter
      run: |
          dotnet fsharplint lint FsSolution/Problem7.fs
          dotnet fsharplint lint FsSolution/Problem26.fs
          dotnet fsharplint lint FsSolution/Program.fs
  
    - name: Format 
      run: |
        fantomas FsSolution/Problem7.fs
        fantomas FsSolution/Problem26.fs
        fantomas FsSolution/Program.fs

    - name: Run tests
      run: dotnet test Tests/Tests.fsproj --verbosity normal
