name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' 

    - name: Install dependencies
      run: dotnet restore ./FsSolution/FProj.fsproj

    - name: Run tests
      run: dotnet test --no-build --verbosity normal ./FsSolution/FProj.fsproj

    - name: Run linter (FSharpLint)
      run: dotnet fsharplint lint .

    - name: Run Fantomas for auto-formatting
      run: dotnet fantomas .

    - name: Build project (with warnings treated as errors)
      run: dotnet build --no-restore --warnaserror
