name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore FsSolution/FProj.fsproj

    - name: Build the project
      run: dotnet build FsSolution/FProj.fsproj --configuration Debug

    - name: Run FSharpLint
      run: dotnet tool install --global FSharpLint && fsharplint --check FsSolution/*.fs

    - name: Run Fantomas
      run: dotnet tool install --global Fantomas && fantomas FsSolution/*.fs
    - name: Run tests
      run: dotnet test Tests/Tests.fsproj --verbosity normal
