name: .NET 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./FProj.fsproj

    - name: Build project
      run: dotnet build ./
 
    - name: Set DOTNET_ROLL_FORWARD
      run: echo "DOTNET_ROLL_FORWARD=latestMajor" >> $GITHUB_ENV
    - name: Lint
      run: |
          dotnet tool install -g dotnet-fsharplint
          dotnet fsharplint lint ./

    - name: Formatter
      run: |
          dotnet tool install -g fantomas-tool
          fantomas ./*.fs 
        
    - name: Run project
      run: dotnet run --project ./
        
    - name: Tests
      run: |
            dotnet restore Tests/Tests.fsproj
            dotnet build ./Tests
            dotnet test ./Tests