name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore FsSolution/FProj.fsproj

    - name: Build the project
      run: dotnet build FsSolution/FProj.fsproj --configuration Debug

    - name: Create Tool Manifest
      run: dotnet new tool-manifest

    - name: Install FSharpLint
      run: dotnet tool install FSharpLint

    - name: Run FSharpLint
      run: dotnet fsharplint --check FsSolution/FProj/**/*.fs

    - name: Install Fantomas
      run: dotnet tool install Fantomas

    - name: Run Fantomas
      run: dotnet fantomas FsSolution/FProj/**/*.fs

    - name: Run tests
      run: dotnet test Tests/Tests.fsproj --verbosity normal
