name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Install FSharpLint
      run: dotnet tool install -g dotnet-fsharplint

    - name: Install FSharpLint
      run: dotnet tool install -g fantomas

    - name: Restore dependencies
      run: dotnet restore FsSolution/FProj.fsproj

    - name: Build the project
      run: dotnet build FsSolution/FProj.fsproj --configuration Debug

    - name: Linter
      run: |
          cd ../FsSolution
          dotnet fsharplint lint Program.fs
  
    - name: Format 
      run: |
        fantomas Problem7.fs
        fantomas Problem26.fs
        fantomas Program.fs

    - name: Run tests
      run: dotnet test Tests/Tests.fsproj --verbosity normal
