name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Create Tool Manifest
      run: dotnet new tool-manifest

    - name: Install FSharpLint
      run: dotnet tool install FSharpLint

    - name: Install Fantomas
      run: dotnet tool install Fantomas

    - name: Restore dependencies
      run: dotnet restore FsSolution/FProj.fsproj

    - name: Build the project
      run: dotnet build FsSolution/FProj.fsproj --configuration Debug

    - name: Linter
      run: |
          dotnet fsharplint lint FsSolution/Problem7.fs
          dotnet fsharplint lint FsSolution/Problem26.fs
          dotnet fsharplint lint FsSolution/Program.fs
  
    - name: Format 
      run: |
        dotnet fantomas FsSolution/Problem7.fs
        dotnet fantomas FsSolution/Problem26.fs
        dotnet fantomas FsSolution/Program.fs

    - name: Run tests
      run: dotnet test Tests/Tests.fsproj --verbosity normal